### ISSUE TITLE
[BUG] Running ts-prune throws a TypeError: Cannot read property 'map' of undefined

### ISSUE THREAD

**Issue by sebflipper** [nadeesha/ts-prune#59] opened 2020-05-27 09:01 UTC
**Describe the bug**
Running `ts-prune` throws the following error:

```
/Users/seb/.config/yarn/global/node_modules/ts-prune/lib/analyzer.js:107
    return entrypoints.map(function (file) { return ({
                       ^

TypeError: Cannot read property 'map' of undefined
    at emitTsConfigEntrypoints (/Users/seb/.config/yarn/global/node_modules/ts-prune/lib/analyzer.js:107:24)
    at Object.exports.analyze (/Users/seb/.config/yarn/global/node_modules/ts-prune/lib/analyzer.js:118:5)
    at Object.exports.run (/Users/seb/.config/yarn/global/node_modules/ts-prune/lib/runner.js:21:16)
    at Object.<anonymous> (/Users/seb/.config/yarn/global/node_modules/ts-prune/lib/index.js:5:10)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
```

**To Reproduce**
1. `nvm install 12 && nvm use 12`
2. `yarn global add ts-prune`
3. `yarn create react-app my-app --template typescript`
4. `cd my-app`
5. `ts-prune`

**Expected behavior**
`ts-prune` should run correctly.

**Comment by nadeesha** [comment] 2020-05-27 11:21
Thanks for  reporting this. I reckon this is caused by the missing `files` property in tsconfig.json. Fix is incoming.

**Closed** 2020-05-27 11:22 UTC
Labels: bug
