### ISSUE TITLE
False positives on types imported with `import type`

### ISSUE THREAD

**Issue by vaskevich** [nadeesha/ts-prune#52] opened 2020-05-02 01:04 UTC
It's possible that this is an issue with `ts-morph`, but wanted to report this here. The new `import type` syntax introduced in TypeScript 3.8 appears to be resulting in false positives. Here's an example (applying this patch on this repo @ https://github.com/nadeesha/ts-prune/commit/e879ac6e4d29e64fea872205a8d7c37e19256b22):

```patch
diff --git a/src/analyzer.ts b/src/analyzer.ts
index d767698..726f3ba 100644
--- a/src/analyzer.ts
+++ b/src/analyzer.ts
@@ -8,6 +8,7 @@ import {
 } from "ts-morph";
 import { isDefinitelyUsedImport } from "./util/isDefinitelyUsedImport";
 import { getModuleSourceFile } from "./util/getModuleSourceFile";
+import type { SomeType } from "./presenter";
 
 type OnResultType = (result: IAnalysedResult) => void;
 
@@ -22,7 +23,7 @@ export interface IAnalysedResult {
   symbols: Array<string>;
 }
 
-function handleExportDeclaration(node: SourceFileReferencingNodes) {
+function handleExportDeclaration(node: SourceFileReferencingNodes, _someParam?: SomeType) {
   return (node as ExportDeclaration).getNamedExports().map(n => n.getName());
 }
 
diff --git a/src/presenter.ts b/src/presenter.ts
index dcf1320..2115e1e 100644
--- a/src/presenter.ts
+++ b/src/presenter.ts
@@ -15,3 +15,5 @@ export const present = (state: State) => {
 
   return [].concat.apply([], unused2D) as Array<IAnalysedResult>;
 };
+
+export type SomeType = any;
```

This results in:
```
 ➜  ts-prune git:(master) ✗ ts-prune
SomeType @ ./src/presenter.ts
```

**Comment by nadeesha** [comment] 2020-05-22 00:06
Thanks for reporting this. Let me try to find a fix via heuristics.

**Comment by nadeesha** [comment] 2020-05-23 04:42
This is now fixed via #53. Cheers!

**Comment by vaskevich** [comment] 2020-05-27 00:54
Thanks for taking care of this! I updated to use the new version and noticed two issues. Wanted to flag them here in case someone else comes across them, as I think the fixes are pretty easy.

## 1. TypeError

```
TypeError: Reduce of empty array with no initial value
    at Array.reduce (<anonymous>)
    at mustIgnore (/project/node_modules/ts-prune/lib/analyzer.js:41:106)
    at /project/node_modules/ts-prune/lib/analyzer.js:50:45
    at Array.filter (<anonymous>)
    at getExported (/project/node_modules/ts-prune/lib/analyzer.js:50:10)
    at emitPotentiallyUnused (/project/node_modules/ts-prune/lib/analyzer.js:88:20)
    at /project/node_modules/ts-prune/lib/analyzer.js:115:9
    at Array.forEach (<anonymous>)
    at Object.exports.analyze (/project/node_modules/ts-prune/lib/analyzer.js:114:30)
    at Object.exports.run (/project/node_modules/ts-prune/lib/runner.js:21:16)
```

Didn't quite debug where this happened, but looks like the call to `reduce()` is missing an empty array initializer (i.e., `, []` at the end). To address this, I used `patch-package` locally to add that in two places.

## 2. SyntaxError

`tsconfig.json` technically supports comments, but ts-prune throws a SyntaxError when trying to open it: `Unexpected token / in JSON at position 29`. I used [json5](https://www.npmjs.com/package/json5) to rewrite the file before feeding into `ts-prune`, so perhaps this project can use that too instead of `require`ing the config file directly.

**Comment by nadeesha** [comment] 2020-05-27 11:50
Thanks @vaskevich. I've fixed both of the issues in [0.6.3](https://github.com/nadeesha/ts-prune/releases/tag/v0.6.3)

The `TypeError` you've mentioned is a bit alien to me. Mind telling me which node version this is?

**Comment by vaskevich** [comment] 2020-05-27 16:11
Awesome! I believe I was using Node 12.

**Comment by nadeesha** [comment] 2020-05-28 23:22
I couldn't reproduce this is node 12 btw. Maybe something else is at play here. Anyways, thanks for reporting!

**Closed by nadeesha** 2020-05-28 23:22 UTC
Labels: bug, help wanted

**Comment by JustFly1984** [comment] 2020-05-29 00:28
@nadeesha  `import type` is supported by @babel/core 6.9.0 and newer
current version is 7.1.1
